### ISSUE TITLE
Doesn't work on Remi 9c NFC 

### ISSUE THREAD

**Issue by DevT0ha** [Magisk-Modules-Repo/ARCore_enabler#11]
Hello

After installation in magisk, fingerprint changed, but i wasn't able to download ar core from google play(it showed unsupported device), so i installed last version (1.23.210260663 ) from apk. 

I tested ar apps form google play, but they didnt work.
Apps starts, interface work, but camera doesn't work (black screen).

Logcat of Ar Core, when launching ar apps: 
` 22:26:13.142 31615 31615 E ARCore-LocationProvider:       at com.google.ar.core.services.LocationProvider.loadClass(PG:1)
02-27 22:26:13.142 31615 31615 E ARCore-LocationProvider:       at com.google.ar.core.services.LocationProvider.setupFusedLocationProviderApi(PG:1)
02-27 22:26:13.142 31615 31615 E ARCore-LocationProvider:       at com.google.ar.core.services.LocationProvider.<init>(PG:7)
02-27 22:26:13.142 31615 31615 E ARCore-LocationProvider:       at com.google.ar.core.Session.nativeCreateSessionAndWrapper(Native Method)
02-27 22:26:13.142 31615 31615 E ARCore-LocationProvider:       at com.google.ar.core.Session.<init>(Unknown Source:18)
02-27 22:26:13.255 31615 31615 I native  : app_version_util.cc:50 Package name: com.google.ar.core App version: 1.23.210260623
02-27 22:26:13.654  2612  2629 I MdiSyncModule: Receiving API connection from package 'com.google.ar.core'...
02-27 22:26:13.999 31615 31707 E DrawARActivity: com.google.ar.core.exceptions.SessionPausedException
02-27 22:26:13.999 31615 31707 E DrawARActivity:        at com.google.ar.core.Session.throwExceptionFromArStatus(Unknown Source:72)
02-27 22:26:13.999 31615 31707 E DrawARActivity:        at com.google.ar.core.Session.nativeUpdate(Native Method)
02-27 22:26:13.999 31615 31707 E DrawARActivity:        at com.google.ar.core.Session.update(Unknown Source:9)`

Maybe they changed somethings after last update?

**Comment by DevCasty** [comment]
> Hello, I've look into and the "trick" that this module uses, does not work on 32 bit operating systems, like MIUI on your Redmi. The only way for you to have it working would be install a 64 bit OS (a custom Rom should be ok).

Thank you

**Comment by MarcAnt01** [comment]
After further checks, there seem no way to make Arcore working on Arm32 devices. Closing this
